language: python

services:
    - docker

install:
    - docker pull keyiz/manylinux_igraph
    - docker run -d --name manylinux --rm -i -t keyiz/manylinux_igraph bash

script:
    - docker exec manylinux git clone https://github.com/Kuree/cgra_pnr
    - docker exec -i manylinux bash -c "cd cgra_pnr && git submodule update --init --recursive"
    - docker exec -i manylinux bash -c 'cd cgra_pnr/thunder && for PYBIN in /opt/python/*/bin; do "${PYBIN}/python" setup.py bdist_wheel; done'
    - docker exec -i manylinux bash -c 'cd cgra_pnr/cyclone && for PYBIN in /opt/python/*/bin; do "${PYBIN}/python" setup.py bdist_wheel; done'
    - docker exec -i manylinux bash -c 'cd cgra_pnr/thunder && for WHEEL in dist/*.whl; do auditwheel repair "${WHEEL}"; done'
    - docker exec -i manylinux bash -c 'cd cgra_pnr/cyclone && for WHEEL in dist/*.whl; do auditwheel repair "${WHEEL}"; done'

after_success:
    - echo [distutils]                                  > ~/.pypirc
    - echo index-servers =                             >> ~/.pypirc
    - echo "  pypi"                                    >> ~/.pypirc
    - echo                                             >> ~/.pypirc
    - echo [pypi]                                      >> ~/.pypirc
    - echo repository=https://upload.pypi.org/legacy/  >> ~/.pypirc
    - echo username=keyi                               >> ~/.pypirc
    - echo password=$PYPI_PASSWORD                     >> ~/.pypirc
    - docker cp ~/.pypirc manylinux:/home/
    - docker -exec -i manylinux bash -c 'cd cgra_pnr/thunder && twine upload --config-file /home/.pypirc dist/wheelhouse/*'
    - docker -exec -i manylinux bash -c 'cd cgra_pnr/cyclone && twine upload --config-file /home/.pypirc dist/wheelhouse/*'

